#controlplane ~ ➜  cat replicaset-definition-1.yaml 
apiVersion: apps/v1
kind: ReplicaSet
metadata:
   name: replicaset-1
spec:
   replicas: 2
   selector:
      matchLabels:
        tier: front-end
   template:
     metadata:
       labels:
        tier: front-end
     spec:
       containers:
       - name: nginx
         image: nginx

//* controlplane ~ ➜  kubectl create -f replicaset-definition-1.yaml 
replicaset.apps/replicaset-1 created

controlplane ~ ➜  kubectl get rs
NAME           DESIRED   CURRENT   READY   AGE
app-1          3         3         3       9m45s
app-2          1         1         1       9m45s
db-1           4         4         4       9m45s
db-2           1         1         1       9m45s
replicaset-1   2         2         2       9s
*//